version: "3"

services:
  postgres:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - .data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./api:/api

  ui:
    build:
      context: ./ui
    depends_on:
      - api
    env_file: .env
    ports:
      - "${UI_PORT}:${UI_PORT}"
    volumes:
      - ./ui/src:/src
      - ./ui/webpack.config.mjs:/webpack.config.mjs/
      - ./ui/.babelrc:/.babelrc/
