FROM python:3.12 as base
ARG API_PORT

ENV YOUR_ENV="envName" \
    PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    # Poetry's configuration:
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_CACHE_DIR='/var/cache/pypoetry' \
    POETRY_HOME='/usr/local' \
    POETRY_VERSION=1.2.0 \
    FLASK_RUN_PORT=${API_PORT}


RUN curl -sSL https://install.python-poetry.org | python3 -
COPY poetry.lock pyproject.toml /
RUN poetry install --no-interaction --no-ansi
COPY . .


FROM base as api-dev
# RUN python3 src/app.py
CMD ["python", "src/app.py"] 